'use client'
import { Download, RefreshCw, Clock, AlertTriangle, CheckCircle, XCircle, Lightbulb, BarChart2 } from 'lucide-react'
import type { PostMortemOutput, IncidentInput } from '@/lib/types'
import { SEVERITY_LABELS } from '@/lib/config'

interface Props {
  output: PostMortemOutput
  input: IncidentInput
  onReset: () => void
}

const TYPE_COLOR: Record<string, string> = {
  preventive: 'rgba(59,130,246,0.15)',
  detective: 'rgba(245,158,11,0.15)',
  corrective: 'rgba(16,185,129,0.15)',
}
const TYPE_TEXT: Record<string, string> = {
  preventive: '#60A5FA',
  detective: '#FCD34D',
  corrective: '#34D399',
}
const PRIORITY_COLOR: Record<string, string> = {
  high: '#EF4444',
  medium: '#F59E0B',
  low: '#10B981',
}
const TIMELINE_COLOR: Record<string, string> = {
  detection: '#EF4444',
  response: '#F97316',
  mitigation: '#F59E0B',
  resolution: '#10B981',
  communication: '#3B82F6',
}

function Section({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl overflow-hidden" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
      <div className="flex items-center gap-2 px-5 py-3 border-b" style={{ borderColor: 'var(--border-default)', background: 'var(--bg-elevated)' }}>
        <span style={{ color: 'var(--accent-red)' }}>{icon}</span>
        <h3 className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{title}</h3>
      </div>
      <div className="p-5">{children}</div>
    </div>
  )
}

function exportMarkdown(output: PostMortemOutput, input: IncidentInput): string {
  const sev = SEVERITY_LABELS[input.severity]
  const lines: string[] = [
    `# Incident Post-Mortem: ${input.title}`,
    `**Severity:** ${sev.label} | **Duration:** ${input.startTime} → ${input.resolvedTime}`,
    `**Affected Systems:** ${input.affectedSystems}`,
    ``,
    `## Executive Summary`,
    output.executiveSummary,
    ``,
    `## Metrics & Impact`,
    output.metricsImpact,
    ``,
    `## Incident Timeline`,
    ...output.timeline.map(e => `- **${e.time}** [${e.type.toUpperCase()}] ${e.event}`),
    ``,
    `## Root Cause`,
    output.rootCause,
    ``,
    `## 5-Whys Analysis`,
    ...output.fiveWhys.map((w, i) => `${i + 1}. ${w}`),
    ``,
    `## Contributing Factors`,
    ...output.contributingFactors.map(f => `- ${f}`),
    ``,
    `## What Worked`,
    ...output.whatWorked.map(w => `- ✓ ${w}`),
    ``,
    `## What Didn't Work`,
    ...output.whatDidntWork.map(w => `- ✗ ${w}`),
    ``,
    `## Action Items`,
    `| Action | Owner | Timeline | Type | Priority |`,
    `|--------|-------|----------|------|----------|`,
    ...output.actionItems.map(a => `| ${a.action} | ${a.ownerRole} | ${a.timeline} | ${a.type} | ${a.priority} |`),
    ``,
    `## Lessons Learned`,
    output.lessonsLearned,
    ``,
    `---`,
    `*Generated by Post-Mortem AI — review before distribution*`,
  ]
  return lines.join('\n')
}

export default function PostMortemReport({ output, input, onReset }: Props) {
  const sev = SEVERITY_LABELS[input.severity]

  function handleExport() {
    const md = exportMarkdown(output, input)
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `postmortem-${input.title.toLowerCase().replace(/\s+/g, '-').slice(0, 40)}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      {/* Report header */}
      <div className="rounded-2xl p-5" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <div className="flex items-center gap-2 flex-wrap mb-2">
              <span className="text-xs font-bold px-2.5 py-1 rounded-full"
                style={{ background: sev.bg, color: sev.color }}>
                {sev.label}
              </span>
              {input.startTime && input.resolvedTime && (
                <span className="flex items-center gap-1 text-xs px-2.5 py-1 rounded-full"
                  style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)' }}>
                  <Clock size={11} /> {new Date(input.startTime).toLocaleString()} → {new Date(input.resolvedTime).toLocaleString()}
                </span>
              )}
            </div>
            <h1 className="text-xl font-bold" style={{ color: 'var(--text-primary)' }}>{input.title}</h1>
            {input.affectedSystems && (
              <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
                Systems: {input.affectedSystems}
              </p>
            )}
          </div>
          <div className="flex gap-2">
            <button onClick={handleExport}
              className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold"
              style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-default)' }}>
              <Download size={14} /> Export .md
            </button>
            <button onClick={onReset}
              className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold text-white"
              style={{ background: 'var(--accent-grad)' }}>
              <RefreshCw size={14} /> New Incident
            </button>
          </div>
        </div>
      </div>

      {/* Executive Summary */}
      <Section icon={<BarChart2 size={15} />} title="Executive Summary">
        <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.executiveSummary}</p>
        {output.metricsImpact && (
          <div className="mt-3 p-3 rounded-xl text-sm" style={{ background: 'rgba(239,68,68,0.07)', border: '1px solid rgba(239,68,68,0.2)', color: '#FCA5A5' }}>
            📊 {output.metricsImpact}
          </div>
        )}
      </Section>

      {/* Timeline */}
      <Section icon={<Clock size={15} />} title="Incident Timeline">
        <div className="relative pl-6 space-y-3">
          <div className="absolute left-2 top-2 bottom-2 w-px" style={{ background: 'var(--border-default)' }} />
          {output.timeline.map((event, i) => (
            <div key={i} className="relative">
              <div className="absolute -left-[18px] w-2.5 h-2.5 rounded-full border-2 mt-1"
                style={{ background: TIMELINE_COLOR[event.type] ?? 'var(--accent-red)', borderColor: 'var(--bg-card)' }} />
              <div className="flex items-start gap-3">
                <span className="text-xs font-mono font-bold shrink-0 mt-0.5" style={{ color: TIMELINE_COLOR[event.type] ?? 'var(--accent-red)', minWidth: '3rem' }}>
                  {event.time}
                </span>
                <div>
                  <span className="text-[10px] font-bold uppercase px-1.5 py-0.5 rounded mr-1.5"
                    style={{ background: `${TIMELINE_COLOR[event.type] ?? '#EF4444'}22`, color: TIMELINE_COLOR[event.type] ?? 'var(--accent-red)' }}>
                    {event.type}
                  </span>
                  <span className="text-sm" style={{ color: 'var(--text-secondary)' }}>{event.event}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Root Cause + 5 Whys */}
      <Section icon={<AlertTriangle size={15} />} title="Root Cause Analysis">
        <div className="mb-4 p-3 rounded-xl" style={{ background: 'rgba(239,68,68,0.07)', border: '1px solid rgba(239,68,68,0.2)' }}>
          <p className="text-xs font-bold mb-1" style={{ color: 'var(--accent-red)' }}>Root Cause</p>
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.rootCause}</p>
        </div>
        <p className="text-xs font-bold mb-3 uppercase tracking-wider" style={{ color: 'var(--text-dimmer)' }}>5-Whys Drill-Down</p>
        <div className="space-y-2">
          {output.fiveWhys.map((why, i) => (
            <div key={i} className="flex gap-3 items-start">
              <span className="w-6 h-6 rounded-full text-xs font-bold flex items-center justify-center shrink-0 mt-0.5"
                style={{ background: 'var(--accent-grad)', color: 'white' }}>
                {i + 1}
              </span>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{why.replace(/^Why \d+:\s*/i, '')}</p>
            </div>
          ))}
        </div>
        {output.contributingFactors.length > 0 && (
          <div className="mt-4 pt-4 border-t" style={{ borderColor: 'var(--border-default)' }}>
            <p className="text-xs font-bold mb-2 uppercase tracking-wider" style={{ color: 'var(--text-dimmer)' }}>Contributing Factors</p>
            <ul className="space-y-1">
              {output.contributingFactors.map((f, i) => (
                <li key={i} className="text-sm flex gap-2" style={{ color: 'var(--text-secondary)' }}>
                  <span style={{ color: 'var(--accent-amber)' }}>⚠</span> {f}
                </li>
              ))}
            </ul>
          </div>
        )}
      </Section>

      {/* What Worked / Didn't */}
      <div className="grid grid-cols-2 gap-4">
        <div className="rounded-2xl overflow-hidden" style={{ background: 'var(--bg-card)', border: '1px solid rgba(16,185,129,0.25)' }}>
          <div className="flex items-center gap-2 px-4 py-3 border-b" style={{ borderColor: 'rgba(16,185,129,0.2)', background: 'rgba(16,185,129,0.06)' }}>
            <CheckCircle size={14} style={{ color: '#10B981' }} />
            <span className="text-sm font-bold" style={{ color: '#10B981' }}>What Worked</span>
          </div>
          <ul className="p-4 space-y-2">
            {output.whatWorked.map((w, i) => (
              <li key={i} className="text-sm flex gap-2" style={{ color: 'var(--text-secondary)' }}>
                <span style={{ color: '#10B981' }}>✓</span> {w}
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-2xl overflow-hidden" style={{ background: 'var(--bg-card)', border: '1px solid rgba(239,68,68,0.25)' }}>
          <div className="flex items-center gap-2 px-4 py-3 border-b" style={{ borderColor: 'rgba(239,68,68,0.2)', background: 'rgba(239,68,68,0.06)' }}>
            <XCircle size={14} style={{ color: '#EF4444' }} />
            <span className="text-sm font-bold" style={{ color: '#EF4444' }}>What Didn&apos;t Work</span>
          </div>
          <ul className="p-4 space-y-2">
            {output.whatDidntWork.map((w, i) => (
              <li key={i} className="text-sm flex gap-2" style={{ color: 'var(--text-secondary)' }}>
                <span style={{ color: '#EF4444' }}>✗</span> {w}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Action Items */}
      <Section icon={<CheckCircle size={15} />} title="Action Items">
        <div className="space-y-3">
          {output.actionItems.map((item, i) => (
            <div key={i} className="p-4 rounded-xl flex items-start gap-4"
              style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
              <div className="w-6 h-6 rounded-full text-xs font-bold flex items-center justify-center shrink-0 mt-0.5"
                style={{ background: 'var(--bg-card)', color: 'var(--text-dimmer)', border: '1px solid var(--border-default)' }}>
                {i + 1}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>{item.action}</p>
                <div className="flex items-center gap-2 mt-1.5 flex-wrap">
                  <span className="text-xs px-2 py-0.5 rounded-full font-medium"
                    style={{ background: TYPE_COLOR[item.type] ?? 'var(--bg-elevated)', color: TYPE_TEXT[item.type] ?? 'var(--text-secondary)' }}>
                    {item.type}
                  </span>
                  <span className="text-xs font-bold" style={{ color: PRIORITY_COLOR[item.priority] ?? 'var(--text-dimmer)' }}>
                    {item.priority.toUpperCase()} priority
                  </span>
                  <span className="text-xs" style={{ color: 'var(--text-dimmer)' }}>· {item.ownerRole}</span>
                  <span className="text-xs" style={{ color: 'var(--text-dimmer)' }}>· {item.timeline}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Lessons Learned */}
      <Section icon={<Lightbulb size={15} />} title="Lessons Learned">
        <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.lessonsLearned}</p>
      </Section>
    </div>
  )
}
